version: '3.9'
services:
  hardhat:
    build: .
    ports:
      - "8545:8545"
    volumes:
      - .:/app
    tty: true

  frontend:
    build:
      context: ./frontend
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - hardhat